language: node_js
node_js:
  - "6"
  - "8"
branches:
  only:
  - master
  - dev

install:
  - npm install -g codecov istanbul
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha test/mocha.js
  - codecov
